sudo: required

services:
  - docker

before_install:
  - docker build -t nacho270/test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nacho270/test npm run test

after_success:
  - docker build -t nacho270/docker-fibonacci-calculator-client ./client
  - docker build -t nacho270/docker-fibonacci-calculator-nginx ./nginx
  - docker build -t nacho270/docker-fibonacci-calculator-server ./server
  - docker build -t nacho270/docker-fibonacci-calculator-worker ./worker

  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker hub
  - docker push nacho270/docker-fibonacci-calculator-client
  - docker push nacho270/docker-fibonacci-calculator-nginx
  - docker push nacho270/docker-fibonacci-calculator-server
  - docker push nacho270/docker-fibonacci-calculator-worker

deploy:
  # edge: true - for  missing bucket_name error
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-fibonacci-calculator"
  env: "DockerFibonacciCalculator-env"
  bucket_name: "elasticbeanstalk-eu-west-2-063131236371"
  bucket_path: "docker-fibonacci-calculator"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
